### PR TITLE
Qubes menu improvement

### PR DESCRIPTION
**Pull request by ij1**
This pull request adds hooks for filtering during menu building which enables structuring the awesome menu better (e.g., separate submenus for Templates and sys-.* VMs).

Unfortunately this cannot be made 100% compatible with pre-existing copies an user might have made out of rc.lua as I had to rip the Qubes manager menuitem from qubes.make_menu to a separate function (in order to avoid adding it to each submenu). That is, the Qubes manager menuitem will be lacking after an update unless the user adapts rc.lua manually.

### CODE REVIEW

**Comment by marmarek** [comment]
As this is incompatible change, we can only introduce it in the next major Qubes release (4.0) and include info about incompatibility in release notes/upgrade instruction.

Can you provide a hint on how exactly rc.lua should be updated?

@woju can you review this?

**Comment by ij1** [comment]
Previously: qubes.make_menu() added Qubes Manager menuitem to end of the menu. This was ok since it was called only to create the main menu.

Now: qubes.make_menu() can be called for second (or nth) time when making a submenu:
- The first call creates the menu like now but filters TemplateVMs away from it
- The second call adds submenu for templates with filter including only them.
- etc.

So the needed change effectively is to add the Qubes Manager item to the place user wants it (qubes.manager_menuitem() is provided for creating that).

However, I now have come to second thoughts on this. Maybe qubes.make_menu() should still keep adding the manager menuitem (keeping it compatible) and I should just add another function such as qubes.make_vms_menu(...) for all but adding the manager item but that would be a bad name IMHO as there's already qubes.make_vm_menu(...). In linux kernel I'd just add __make_menu() but I guess that might not be very luaish name.

**Comment by woju** [comment]
I'd very much prefer a new function name, to keep backwards compatibility. May I suggest ``qubes.make_menu_filtered()``, ``.make_filtered_menu()`` or even ``.make_menu_with_filter()``? So people won't have to update their ``rc.lua``.

That said, @marmarek: forcing people to rewrite ``rc.lua``, though not a common practice, is not unheard of in awesome community and has probably many precedents.

I did read through the code and it seems fine, but I didn't actually run it. Should I?

**Comment by ij1** [comment]
Thanks a lot for the review and for the naming suggestions (I'm often having trouble coming up sensible names myself). I'll pick one of those names and do another pull req.

If it counts anything, I've built all those steps using qubes-builder and extracted both rc.lua and qubes.lua out of the rpms and tested them one step at a time. In addition, the final result is obviously what I'm currently running with. (And I'll do similar testing for the stuff in the upcoming pull req.)

**Pull request closed without merging**
