### PR TITLE
Qubes menu improvement (v2)

### PR DESCRIPTION
**Pull request by ij1**
This pull request adds hooks for filtering during menu building which enables structuring the awesome menu better (e.g., separate submenus for Templates and sys-.* VMs).

This is the updated version of earlier PR #3 but this time I added qubes.make_menu_with_filter(). The pre-existing qubes.make_menu() retains the current functionality so rc.lua editing is not needed as it was with #3.

Edit: As it seemed natural to delay extracting qubes.manager_menuitem() from qubes.make_menu() to a later point in the patch series, the series is reordered from what was used in #3 .

### CODE REVIEW

**Comment by ij1** [comment]
ping

**Comment by ij1** [comment]
ping

**Comment by marmarek** [comment]
ping forward: @woju

**Comment by woju** [comment]
Just merged. Thanks for the contribution, and sorry for the delay.

**Pull request merged**
