### PR TITLE
Migrate to Awesome 4.2

### PR DESCRIPTION
**Pull request by kalkin**
The only thing still broken is the menu, but given that the current `HEAD` doesn't work on current Qubes R4.0 (at least for me) I think this is acceptable 😁

### CODE REVIEW

**Comment by kalkin** [comment]
Travis fails because it tries to build Awesome on Fedora 23, which is missing essential dependencies.

**Comment by marmarek** [comment]
> Travis fails because it tries to build Awesome on Fedora 23, which is missing essential dependencies.

Can you switch it to fc25 then? Just edit `.travis.yml`. Update Qubes version to 4.0 there too.

**Comment by marmarek** [comment]
Strange, it still used fc23. I'll cherry-pick .travis.yml change to master branch (since we need it anyway) and restart the build.

**Comment by kalkin** [comment]
I upgraded Awesome to `4.2` because it fixes a menubar bug. I also added a patch which enables the QubesOS specific menubar. For now it's just a dummy which displays `qubes-manager` shortcut, but at least it works now.

> The menubar has been fixed for Lua 5.1 users

**Comment by 3hhh** [comment]
Note:

You're re-introducing a bug here that I had previously fixed: Users may want to start windows unfocused depending on their rc.lua config and thus would expect the window border color to behave that way. I do...

```lua
     --set the initial border color
 -    qubes.set_border_colour(c)
 +    c.border_color = qubes.get_colour_focus(c)
  end
```

**Comment by marmarek** [comment]
Some patches (like dex-autostart or use-vi-instead-of-nano) lost their description and/or authorship.

**Comment by kalkin** [comment]
@3hh & @marmarek thanks for the hints. Will fix that tomorrow.

**Comment by kalkin** [comment]
Also please don't merge until i have fixed menus. I'm mostly finished it.

**Comment by kalkin** [comment]
- Fixed regression @3hhh mentioned
- Fixed authorship & description for vim & dex patch

**Comment by kalkin** [comment]
Contrary to my comment before, you can merge this patch even without menu integration, because this PR is already getting very big and menu integration will take some time.

**Comment by 3hhh** [comment]
Thanks @kalkin !

**Review by woju — COMMENTED** [review]
I'm reluctant to approve. Awesome in fc25 is still 3.5.9 and I don't see the reason to bump it to 4.2. Could you elaborate why we need to upgrade it? In the past there were some major incompatibilities around specific versions of lua (modules loading) vs awesome and this might break some configs.

Not that awesomewm users would care very much. I know no awesome extension in fedora repos anyway.

@kalkin @3hhh

**Comment by kalkin** [comment]
@woju I know there was some bug, which was fixed in Awesome 4.0, that in combination with QubesOS, annoyed me so much, that I went back to XFCE. Sadly I can't remember what the issue was.

@marmarek I remember I complained to you via XMPP, about the bug and that I couldn't build Awesome 4.0 because of missing dependencies in `dom0` for R3.2. I can't find the logs, may be you can find it?

**Comment by kalkin** [comment]
@woju I went back to using Awsome on R3.2 to check what the issue was. It's the hiding of some parts of the ui, like the Firefox url bar completion. Currently I can't reproduce the bug in R4, but I'm still testing

@3hhh Are you using Awsome on R4? Can you report if the bug still shows up?

**Comment by 3hhh** [comment]
@kalkin Yes, I do use awesome on 4.0rc1.

I noticed some GUI issues here and there, but nothing severe. E.g.

- Some Windows don't adhere or stretch to the selected layout, but I guess that's normal (probably depends on the Window properties selected by the programmer). This includes the Qubes Manager in 3.2 (not an issue in 4 as it doesn't exist anymore).
- l recall that the libreoffice calc Right-Click context menu was behaving strangely in the past.
- Focus steals can occur e.g. when you start a VM and are still typing in a different VM window during the meantime. It's possible to fix that in one's rc.lua if one finds it annoying though. I have a focus steal hardened version, but I guess it's not really interesting for the general audience.

**Pull request closed without merging**
