### PR TITLE
Port of Awesome v4.3 for QubesOS R4.1

### PR DESCRIPTION
**Pull request by kalkin**
This needs https://github.com/kalkin/qubes-desktop-linux-dex for autostarting stuff on startup.

[Original Issue](https://github.com/QubesOS/qubes-issues/issues/6418)

### CODE REVIEW

**Comment by 3hhh** [comment]
Thanks for working on this @kalkin , much appreciated!

**Comment by fepitre** [comment]
@kalkin why is it really necessary to have your version of `dex` as it is available in Fedora 32? Also, can you try to solve conflict? Else, I can do it but I would also switch it to `spec.in` form.

**Comment by kalkin** [comment]
@fepitre Missed that dex is already in Fedora-32. Will switch to that. Will fix conflicts.

**Comment by marmarek** [comment]
I'll fixup the merge conflict and make it pass the trivial "does it start" test. But it may still require more love...

**Pull request merged**
